location.ancestorOrigins
location.assign
location.constructor
location.hasOwnProperty
location.hash
location.host
location.hostname
location.href
location.isPrototypeOf
location.origin
location.pathname
location.port
location.propertyIsEnumerable
location.protocol
location.reload
location.replace
location.search
location.toLocaleString()
location.toString()
location.valueOf()