console.log(location.ancestorOrigins);//
console.log(location.assign);
console.log(location.constructor);
console.log(location.hasOwnProperty);//
console.log("AAAAA");
console.log(location.hash);
console.log(location.host);
console.log(location.hostname);
console.log(location.href);
console.log(location.isPrototypeOf);//
console.log(location.origin);//
console.log(location.pathname);
console.log(location.port);
console.log(location.propertyIsEnumerable);//
console.log(location.protocol);
console.log(location.reload);
console.log(location.replace);
console.log(location.search);
console.log(location.toLocaleString());//
console.log(location.toString());
console.log(location.valueOf());//