console.log(location.ancestorOrigins);//
console.log(location.hasOwnProperty);//
console.log(location.isPrototypeOf);//
console.log(location.origin);//
console.log(location.propertyIsEnumerable);//
console.log(location.toLocaleString);//
console.log(location.valueOf);//
console.log("AAAAA");
console.log(location.hash);
console.log(location.host);
console.log(location.hostname);
console.log(location.search);
console.log(location.port);
console.log("AAAAA2");
console.log(location.assign);
console.log(location.constructor);
console.log(location.href);
console.log(location.pathname);
console.log(location.protocol);
console.log(location.reload);
console.log(location.replace);
console.log(location.toString());
console.log("BBBBB");

//replace("abcde","abc","v")
//"vde"
//replace("abcde","abc","xyz")
//"xyzde"
//replace("abcde","cde","xyz")
//"abxyz"
//replace("cde","cde","xyz")
//"xyz"
//replace("cde","cde","")
//""
//replace("abcde","cde","")
//"ab"
//replace("abcdef","cde","")
//"abf"
//replace("abcdef","","")
//"abcdef"
//replace("abcdef","","xyz")
//"abcdef"
//replace("abcdef",null,"xyz")
//icejs.js:49 Uncaught TypeError: Cannot read property 'length' of null(…)replace @ icejs.js:49(anonymous function) @ VM2025:2InjectedScript._evaluateOn @ VM2009:904InjectedScript._evaluateAndWrap @ VM2009:837InjectedScript.evaluate @ VM2009:693
//replace("abcdef","abc",null)
//"abcdef"
//replace(null,"abc","def")
//null