console.log(String.prototype.anchor);
console.log(String.prototype.big);
console.log(String.prototype.blink);
console.log(String.prototype.bold);
console.log(String.prototype.charAt);
console.log(String.prototype.charCodeAt);
console.log(String.prototype.concat);
console.log(String.prototype.constructor);
console.log(String.prototype.endsWith);//
console.log(String.prototype.fixed);
console.log(String.prototype.fontsize);
console.log(String.prototype.hasOwnProperty);
console.log(String.prototype.includes);//
console.log(String.prototype.indexOf);
console.log(String.prototype.isPrototypeOf);
console.log(String.prototype.italics);
console.log(String.prototype.lastIndexOf);
console.log(String.prototype.length);//0
console.log(String.prototype.link);
console.log(String.prototype.localeCompare);
console.log(String.prototype.match);
console.log(String.prototype.normalize);//
console.log(String.prototype.propertyIsEnumerable);
console.log(String.prototype.repeat);//
console.log(String.prototype.replace);
console.log(String.prototype.search);
console.log(String.prototype.slice);
console.log(String.prototype.small);
console.log(String.prototype.split);
console.log(String.prototype.startsWith);//
console.log(String.prototype.strike);
console.log(String.prototype.sub);
console.log(String.prototype.substr);
console.log(String.prototype.substring);
console.log(String.prototype.sup);
console.log(String.prototype.toLocaleLowerCase);
console.log(String.prototype.toLocaleString);
console.log(String.prototype.toLocaleUpperCase);
console.log(String.prototype.toLowerCase);
console.log(String.prototype.toString);
console.log(String.prototype.toUpperCase);
console.log(String.prototype.trim);//
console.log(String.prototype.trimLeft);//
console.log(String.prototype.trimRight);//
console.log(String.prototype.valueOf);
