console.log(Array.prototype.concat);
console.log(Array.prototype.constructor);
console.log(Array.prototype.copyWithin);//
console.log(Array.prototype.entries);//
console.log(Array.prototype.every);//
console.log(Array.prototype.fill);//
console.log(Array.prototype.filter);//
console.log(Array.prototype.find);//
console.log(Array.prototype.findIndex);//
console.log(Array.prototype.forEach);//
console.log(Array.prototype.hasOwnProperty);
console.log(Array.prototype.indexOf);//
console.log(Array.prototype.isPrototypeOf);
console.log(Array.prototype.join);
console.log(Array.prototype.keys);//
console.log(Array.prototype.lastIndexOf);//
console.log(Array.prototype.length);
console.log(Array.prototype.map);//
console.log(Array.prototype.pop);
console.log(Array.prototype.propertyIsEnumerable);
console.log(Array.prototype.push);
console.log(Array.prototype.reduce);//
console.log(Array.prototype.reduceRight);//
console.log(Array.prototype.reverse);
console.log(Array.prototype.shift);
console.log(Array.prototype.slice);
console.log(Array.prototype.some);//
console.log(Array.prototype.sort);
console.log(Array.prototype.splice);
console.log(Array.prototype.toLocaleString);
console.log(Array.prototype.toString);
console.log(Array.prototype.unshift);
console.log(Array.prototype.valueOf);
