location.ancestorOrigins
location.assign
constructor
hasOwnProperty
location.hash
location.host
location.hostname
location.href
isPrototypeOf
location.origin
location.pathname
location.port
propertyIsEnumerable
location.protocol
location.reload
location.replace
location.search
toLocaleString
location.toString
location.valueOf